version: '3'

services:
    php-apache:
        container_name: phptest-php-apache
        build: .
        volumes:
            - ./php_test_app/:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - db
        links:
            - db

    db:
        container_name: phptest-db
        image: mysql
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        env_file:
            - db.env

