<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title><?php echo $tparams['params']['title']; ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
        body {
            padding-top: 1.5em;
        }
    </style>
</head>
<body>
    <div class='container content'>
        <h1><?php echo $tparams['params']['title']; ?></h1>

        <br>
        <form method="post" action="/create_product" class="w-75">
            <div class="form-group">
                <label for="name" class="font-weight-bold">Наименование товара</label>
                <?php if ($tparams['params']['form_error']['name'][1]): ?>
                    <input type="text" name="name" id="name" class="form-control is-invalid" value="<?php echo $tparams['params']['form_error']['name'][0]; ?>" required>
                    <div class="invalid-feedback">
                        <?php echo $tparams['params']['form_error']['name'][1]; ?>
                    </div>
                <?php else: ?>
                    <input type="text" name="name" id="name" class="form-control" value="<?php echo $tparams['params']['form_error']['name'][0]; ?>" required>
                <?php endif ?>
            </div>
            <div class="form-group">
                <label for="quantity" class="font-weight-bold">Количество</label>
                <?php if ($tparams['params']['form_error']['quantity'][1]): ?>
                    <input type="text" name="quantity" id="quantity" class="form-control is-invalid" value="<?php echo $tparams['params']['form_error']['quantity'][0]; ?>" required>
                    <div class="invalid-feedback">
                        <?php echo $tparams['params']['form_error']['quantity'][1]; ?>
                    </div>
                <?php else: ?>
                    <input type="text" name="quantity" id="quantity" class="form-control" value="<?php echo $tparams['params']['form_error']['quantity'][0]; ?>" required>
                <?php endif ?>
            </div>
            <div class="form-group">
                <label for="price" class="font-weight-bold">Цена</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">0.00</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text">РУБ</span>
                    </div>
                    <?php if ($tparams['params']['form_error']['price'][1]): ?>
                        <input type="text" name="price" id="price" class="form-control is-invalid" value="<?php echo $tparams['params']['form_error']['price'][0]; ?>" required>
                        <div class="invalid-feedback">
                            <?php echo $tparams['params']['form_error']['price'][1] ?>
                        </div>
                    <?php else: ?>
                        <input type="text" name="price" id="price" class="form-control" value="<?php echo $tparams['params']['form_error']['price'][0]; ?>" required>
                    <?php endif ?>
                </div>
            </div>
            <button type="submit" name="create_product" value="1" class="btn btn-primary">Добавить</button>
        </form>

        <br>
        <?php if ($tparams['params']['exist_error']): ?>
            <div class="alert alert-danger w-75">
                <?php echo $tparams['params']['exist_error']; ?>
            </div>
        <?php else: ?>
            <?php if ($tparams['params']['product']): ?>
            <br>

            <div class="card w-50">
                <div class="card-header p-3 mb-2 bg-success text-white">
                    Товар добавлен
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><?php echo $tparams['params']['product']->getName(); ?></li>
                    <li class="list-group-item"><?php echo $tparams['params']['product']->getQuantity(); ?></li>
                    <li class="list-group-item"><?php echo $tparams['params']['product']->getPriceForInput(); ?></li>
                </ul>
            </div>
            <?php endif ?>
        <?php endif ?>

        <br>

    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

