<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title><?php echo $tparams['params']['title']; ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
        body {
            padding-top: 1.5em;
        }
    </style>
</head>
<body>
    <div class='container content'>

        <h1><?php echo $tparams['params']['title']; ?></h1>

        <br>
        <table class="table">
            <thead class="text-white bg-info">
                <tr>
                    <th>Наименование</th>
                    <th>Количество</th>
                    <th>Цена/руб</th>
                </tr>
            </thead>
            <?php if ($tparams['params']['products']): ?>
            <?php foreach ($tparams['params']['products'] as $p): ?>
            <tr>
                <td><?php echo $p->getName(); ?></td>
                <td><?php echo $p->getQuantity(); ?></td>
                <td><?php echo $p->getPriceForInput(); ?></td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
        </table>

    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

